### PR TITLE
Add u16, u256, and u512 for ser/de with test

### PR DESCRIPTION
**Pull request by joncinque**
This expands the different possibilities for large unsigned numbers, including `u256` and `u512`.  Also, the implementation for `u16` was missing, so add that in as well!

The `u256` and `u512` are particularly useful for public keys represented as a `BN` in front-end code.

### CODE REVIEW

**Comment by joncinque** [comment]
Let me know what I need to do for the CI -- it seems like there's a missing `FOSSA_API_KEY`

**Review by ailisp — APPROVED** [review]
Thanks!

**Comment by ailisp** [comment]
@volovyk-s @chefsale can we figure out run CI for external contributors like borsh-rs, at least we run some of tests, if there's security concern

**Comment by chefsale** [comment]
@ailisp the problem is that the env variables are not currently applied on the forks and this makes the checks to fail. I will be taking a look on how to make this work.

**Comment by chefsale** [comment]
I think for now we could add a check in travis.yml which skips the fossa integration on forks and than runs it on master eitherway. cc: @ailisp what do you think, this would be a temp solution which isn't optimal, it is non trivial to make this work properly.

**Comment by joncinque** [comment]
What's your approval and release procedure typically?  I'd like to get a sense of when I might be able to integrate these changes in my own code

**Comment by joncinque** [comment]
@chefsale Is there anything else required here? I would like to start using it if possible!

**Comment by ailisp** [comment]
@joncinque sorry for the delay. I've merged the other PR from you. For this one, I create #15 to trigger ci and will merge if pass. Thank you!

**Comment by ailisp** [comment]
@joncinque I merged #15 which includes your commits and resolved conflict, so will close this

**Comment by ailisp** [comment]
@chefsale Sorry somehow I missed these replies. Looks like foss also run tests, can we have some basic test for fork (just npm run test), and foss only on master. For example this build was also on a fork and it works: https://travis-ci.com/github/near/borsh-js/jobs/473781317/config

**Comment by joncinque** [comment]
@ailisp Thanks so much! In the future, do you have a preferred way to communicate?  At Solana, we've started leaning heavily on all of the great Borsh libraries, so we're happy to get in touch however you prefer :smile:

**Comment by ailisp** [comment]
@joncinque Hi Jon, glad to connect! I watch discord frequently. I'm also in solana discord server and my handle is `Bo | NEAR#8394`

**Pull request merged**
